// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO4oBqei9EiIPEj8pIOYly_-Bt-hLCtYg',
    appId: '1:390523830138:web:00aad88a9d7c45525020c3',
    messagingSenderId: '390523830138',
    projectId: 're-exam-eae37',
    authDomain: 're-exam-eae37.firebaseapp.com',
    storageBucket: 're-exam-eae37.appspot.com',
    measurementId: 'G-TYHE2458JT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABCt2pcTYRkJj4ISApmm9K7PRgM1DYIVI',
    appId: '1:390523830138:android:f0c02b5334bb35df5020c3',
    messagingSenderId: '390523830138',
    projectId: 're-exam-eae37',
    storageBucket: 're-exam-eae37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDTEszyhc636QGyN6lTf6ZBHp_epDHiIA',
    appId: '1:390523830138:ios:e27d270a483601c65020c3',
    messagingSenderId: '390523830138',
    projectId: 're-exam-eae37',
    storageBucket: 're-exam-eae37.appspot.com',
    iosBundleId: 'com.example.reExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDTEszyhc636QGyN6lTf6ZBHp_epDHiIA',
    appId: '1:390523830138:ios:e27d270a483601c65020c3',
    messagingSenderId: '390523830138',
    projectId: 're-exam-eae37',
    storageBucket: 're-exam-eae37.appspot.com',
    iosBundleId: 'com.example.reExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDO4oBqei9EiIPEj8pIOYly_-Bt-hLCtYg',
    appId: '1:390523830138:web:237aa2cc460c32995020c3',
    messagingSenderId: '390523830138',
    projectId: 're-exam-eae37',
    authDomain: 're-exam-eae37.firebaseapp.com',
    storageBucket: 're-exam-eae37.appspot.com',
    measurementId: 'G-S46KB7LV00',
  );
}
